### ISSUE TITLE
Improve valkyrie and voltron resources

### ISSUE THREAD

**Issue by paul-jacob** [smartcitiesdata/voltron#56]
As a smrt dev I would like to optimize resources in the data pipeline to improve ingestion performance.

AC: 
    - Scale down number of valkyrie and voltron pods / increase CPU
    - In code (No manually editing deployments)

Tech Note: 
    - At least 2 valk/volt

**Comment by bbrewer-papa-x** [comment]
More input from performance testing:
- We get about 23,000 message per second with:
  - prefetch_bytes: 10_000_000 (this is per topic so keep that in mind for memory limit)
  - prefetch_message: 0 (turns this off in favor of bytes)
  - processor_stages: 8 (2x4 CPU cores)
